-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DCPP_MEMORY \
	-DNDEBUG

TARGET=lgpt

TARGET = lgpt-psp

EXTRA_TARGETS = EBOOT.PBP UsbMidiDriver.prx
PSP_EBOOT_TITLE = LittleGPTracker
PSP_EBOOT_ICON = $(PWD)/psp_icon.png
PSP_EBOOT_PIC1 = $(PWD)/psp_bg.png

PSPSDK=$(shell $(PSPDEV)/bin/psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin

CFLAGS	:=	-O3 -G0 -Wall $(DEFINES) -I$(PWD)/../sources -I$(PSPSDK)/include \
	-I$(PWD)/../psp-usb-midi/dist/PspUsbMidi/include
CXXFLAGS:=	$(CFLAGS) -fexceptions -fno-rtti
LIBS = -L$(PWD)/../psp-usb-midi/dist/PspUsbMidi/lib -lPspUsbMidi \
	-L$(PSPDEV)/psp/lib -lSDL_image -lpng -lz -lstdc++ -lSDL -lGL -lGLU -lglut -lm -lc -ljpeg
LIBS += -lpspvfpu -lpspgu -lpsphprm -lpsprtc -lpspaudio -lpspirkeyb -lpsppower
LIBS += -lpspusb
EXTENSION:= elf
