#include "PSPMidiOutDevice.h"

#include "Application/Player/SyncMaster.h"
#include "System/Console/Trace.h"

#include <pspkernel.h>

extern "C" {
#include <psp_usb_midi.h>
}

PSPMidiOutDevice::PSPMidiOutDevice(const char *name, const char *driverPath)
    : MidiOutDevice(name), driverPath_(driverPath), initialized_(false),
      running_(false), clockRunning_(false), clockThread_(-1),
      usbStartedAt_(0) {}

PSPMidiOutDevice::~PSPMidiOutDevice() { Close(); }

bool PSPMidiOutDevice::Init() {
    if (initialized_) {
        return true;
    }

    int result = UsbMidi_Init(driverPath_.c_str());
    if (result < 0) {
        Trace::Log("PSPMidi", "USB MIDI init failed: 0x%08X",
                   (unsigned int)result);
        return false;
    }

    initialized_ = true;
    return true;
}

void PSPMidiOutDevice::Close() {
    if (!initialized_) {
        return;
    }

    StopClock();
    running_ = false;
    usbStartedAt_ = 0;
    int result = UsbMidi_Shutdown();
    if (result < 0) {
        Trace::Log("PSPMidi", "USB MIDI shutdown failed: 0x%08X",
                   (unsigned int)result);
    } else {
        initialized_ = false;
    }
}

bool PSPMidiOutDevice::Start() {
    if (running_) {
        return true;
    }
    if (!initialized_ && !Init()) {
        return false;
    }

    int result = UsbMidi_Start();
    if (result < 0) {
        Trace::Log("PSPMidi", "USB MIDI start failed: 0x%08X",
                   (unsigned int)result);
        return false;
    }

    running_ = true;
    usbStartedAt_ = sceKernelGetSystemTimeWide();
    return true;
}

void PSPMidiOutDevice::Stop() {
    if (!running_) {
        return;
    }

    StopClock();
    running_ = false;
    usbStartedAt_ = 0;
    int result = UsbMidi_Stop();
    if (result < 0) {
        Trace::Log("PSPMidi", "USB MIDI stop failed: 0x%08X",
                   (unsigned int)result);
    }
}

void PSPMidiOutDevice::SendMessage(MidiMessage &message) {
    if (!running_) {
        return;
    }

    if (message.status_ == 0xF8) {
        // PSP clock is generated by the monotonic clock thread below. The
        // generic LGPT clock follows player updates and can stall while a
        // sample is being loaded.
        return;
    }
    if (message.status_ == 0xFC) {
        StopClock();
    }

    int result = WriteMessage(message);
    if (result >= 0 && message.status_ == 0xFA) {
        StartClock();
    }
}

int PSPMidiOutDevice::WriteMessage(MidiMessage &message) {
    UsbMidiEvent event;

    event.timestamp_us = sceKernelGetSystemTimeLow();
    event.cable = 0;
    event.status = message.status_;
    event.data1 = message.data1_ == MidiMessage::UNUSED_BYTE
                      ? 0
                      : message.data1_;
    event.data2 = message.data2_ == MidiMessage::UNUSED_BYTE
                      ? 0
                      : message.data2_;

    return WriteEvents(&event, 1);
}

int PSPMidiOutDevice::WriteEvents(void *eventBuffer, int count) {
    UsbMidiEvent *events = static_cast<UsbMidiEvent *>(eventBuffer);
    int result = UsbMidi_Write(events, count);
    if (result < 0 && (count != 1 || events[0].status != 0xF8)) {
        Trace::Log("PSPMidi", "USB MIDI write failed: 0x%08X",
                   (unsigned int)result);
    }
    return result;
}

void PSPMidiOutDevice::SendQueue(T_SimpleList<MidiMessage> &queue) {
    if (!running_) {
        return;
    }
    UsbMidiEvent events[PSP_USB_MIDI_MAX_BATCH_EVENTS];
    int count = 0;
    int result = 0;
    IteratorPtr<MidiMessage> iterator(queue.GetIterator());

    for (iterator->Begin(); !iterator->IsDone(); iterator->Next()) {
        MidiMessage &message = iterator->CurrentItem();

        if (message.status_ == 0xF8 || message.status_ == 0xFA
            || message.status_ == 0xFC) {
            if (count > 0) {
                result = WriteEvents(events, count);
                count = 0;
                if (result < 0) {
                    break;
                }
            }
            SendMessage(message);
            continue;
        }

        UsbMidiEvent &event = events[count++];
        event.timestamp_us = sceKernelGetSystemTimeLow();
        event.cable = 0;
        event.status = message.status_;
        event.data1 = message.data1_ == MidiMessage::UNUSED_BYTE
                          ? 0
                          : message.data1_;
        event.data2 = message.data2_ == MidiMessage::UNUSED_BYTE
                          ? 0
                          : message.data2_;

        if (count == PSP_USB_MIDI_MAX_BATCH_EVENTS) {
            result = WriteEvents(events, count);
            if (result < 0) {
                break;
            }
            count = 0;
        }
    }

    if (result >= 0 && count > 0) {
        WriteEvents(events, count);
    }
}

bool PSPMidiOutDevice::StartClock() {
    if (clockRunning_) {
        return true;
    }

    clockRunning_ = true;
    clockThread_ = sceKernelCreateThread(
        "LgptUsbMidiClock", ClockThread, 0x18, 0x1000,
        PSP_THREAD_ATTR_USER, 0);
    if (clockThread_ < 0) {
        Trace::Log("PSPMidi", "MIDI clock thread create failed: 0x%08X",
                   (unsigned int)clockThread_);
        clockRunning_ = false;
        clockThread_ = -1;
        return false;
    }

    PSPMidiOutDevice *device = this;
    int result = sceKernelStartThread(
        clockThread_, sizeof(device), &device);
    if (result < 0) {
        Trace::Log("PSPMidi", "MIDI clock thread start failed: 0x%08X",
                   (unsigned int)result);
        sceKernelDeleteThread(clockThread_);
        clockRunning_ = false;
        clockThread_ = -1;
        return false;
    }
    return true;
}

void PSPMidiOutDevice::StopClock() {
    if (clockThread_ < 0) {
        clockRunning_ = false;
        return;
    }

    clockRunning_ = false;
    int result = sceKernelWaitThreadEnd(clockThread_, 0);
    if (result < 0) {
        Trace::Log("PSPMidi", "MIDI clock thread wait failed: 0x%08X",
                   (unsigned int)result);
        return;
    }
    result = sceKernelDeleteThread(clockThread_);
    if (result < 0) {
        Trace::Log("PSPMidi", "MIDI clock thread delete failed: 0x%08X",
                   (unsigned int)result);
        return;
    }
    clockThread_ = -1;
}

int PSPMidiOutDevice::ClockThread(unsigned int args, void *argp) {
    if (args != sizeof(PSPMidiOutDevice *) || !argp) {
        return sceKernelExitDeleteThread(-1);
    }
    PSPMidiOutDevice *device = *static_cast<PSPMidiOutDevice **>(argp);
    return device->RunClock();
}

int PSPMidiOutDevice::RunClock() {
    unsigned long long nextTick = sceKernelGetSystemTimeWide();
    bool wasConnected = UsbMidi_IsConnected();
    unsigned long long reconnectedAt = 0;

    while (clockRunning_ && running_) {
        unsigned long long now = sceKernelGetSystemTimeWide();
        bool connected = UsbMidi_IsConnected();
        if (!connected) {
            wasConnected = false;
            reconnectedAt = 0;
        } else if (!wasConnected) {
            wasConnected = true;
            reconnectedAt = now;
        }

        bool initialSettleComplete =
            usbStartedAt_ != 0 && now - usbStartedAt_ >= 2000000ULL;
        bool reconnectSettleComplete =
            reconnectedAt == 0 || now - reconnectedAt >= 2000000ULL;
        if (connected && initialSettleComplete && reconnectSettleComplete) {
            MidiMessage clock(0xF8, MidiMessage::UNUSED_BYTE,
                              MidiMessage::UNUSED_BYTE);
            WriteMessage(clock);
        }

        int tempo = SyncMaster::GetInstance()->GetTempo();
        if (tempo < 1) {
            tempo = 120;
        }
        unsigned int interval = 60000000U / (24U * (unsigned int)tempo);
        nextTick += interval;

        now = sceKernelGetSystemTimeWide();
        if (nextTick > now) {
            sceKernelDelayThread((SceUInt)(nextTick - now));
        } else if (now - nextTick > (unsigned long long)interval * 2ULL) {
            // Skip missed deadlines instead of replaying a burst of stale
            // clocks after an exceptional scheduler pause.
            nextTick = now;
        }
    }

    return sceKernelExitThread(0);
}
